const database = {
  class: [
    {
      id: 1,
      name: "Ciência da Computação",
    },
  ],
  schedule: [
    {
      nameClass: [
        "Introdução à filosofia",
        "Matemática C",
        "Algoritmos",
        "Estatística",
        "Informática básica",
        "Probabilidade",
        "Cálculo I",
        "Geometria",
        "Estrutura de dados",
        "Produção textual",
        "Circuitos digitais,",
        "Cáculo II",
        "Prog I",
        "Matemática Discreta",
        "POD",
        "Sistemas digitais",
        "Organização",
        "Grafos",
        "Banco I",
        "Iniciação",
        "Engenharia I",
        "Prog II",
        "Linguagens formais",
        "Banco II",
        "Algebra linear",
        "Sistemas operacionais",
        "Engenharia II",
        "Compiladores",
        "Redes",
        "Historia fronteira",
        "Teoria",
        "Planejamento",
        "Cálculo numérico",
        "Meio ambiente",
        "IA",
        "Comp. Gráfica",
        "Linguagens prog.",
        "Direito",,
        "Tópicos XXI",
        "Direito",
        "TCC II",
        "Tópicos XIII",
        "Tópicos XXXIII",
        "TCC I",
      ],
    }
  ],
};
module.exports = database;
